// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BurnAsset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BurnAsset'](arg1, arg2, arg3, arg4);
}

export function DaemonStatus() {
  return window['go']['main']['App']['DaemonStatus']();
}

export function DeployAsset(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['DeployAsset'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function DisconnectWallet() {
  return window['go']['main']['App']['DisconnectWallet']();
}

export function EditAsset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditAsset'](arg1, arg2, arg3, arg4);
}

export function EmitAsset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EmitAsset'](arg1, arg2, arg3, arg4);
}

export function LaunchWallet(arg1, arg2) {
  return window['go']['main']['App']['LaunchWallet'](arg1, arg2);
}

export function WalletStatus() {
  return window['go']['main']['App']['WalletStatus']();
}
