// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BurnAsset(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function DaemonStatus():Promise<boolean>;

export function DeployAsset(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<boolean>;

export function DisconnectWallet():Promise<boolean>;

export function EditAsset(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function EmitAsset(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function EmitPipe():Promise<void>;

export function LaunchWallet(arg1:string,arg2:string):Promise<boolean>;

export function WalletStatus():Promise<boolean>;
